version: '3.9'
services:
  backend:
    build: ./backend/
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
    ports:
      - 8080:8080
  frontend:
    build: ./frontend/
    ports:
      - 5000:5000
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:      
      - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf